# Generated by Django 4.2.7 on 2025-08-04 06:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="자동차 번호"
                    ),
                ),
                (
                    "driving_experience",
                    models.IntegerField(default=0, verbose_name="운전 경력 (년)"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=1,
                        null=True,
                        verbose_name="성별",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="나이")),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="직업"
                    ),
                ),
                (
                    "residence_area",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="거주지역"
                    ),
                ),
                (
                    "annual_mileage",
                    models.IntegerField(default=12000, verbose_name="연간 주행거리"),
                ),
                (
                    "accident_history",
                    models.IntegerField(default=0, verbose_name="사고 이력"),
                ),
                ("car_info", models.JSONField(default=dict, verbose_name="차량 정보")),
                (
                    "selected_insurance",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="선택한 보험상품"
                    ),
                ),
                (
                    "satisfaction_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="만족도 점수",
                    ),
                ),
                (
                    "selection_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="보험 선택일"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필",
            },
        ),
        migrations.CreateModel(
            name="MLRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommended_products",
                    models.JSONField(default=list, verbose_name="추천 상품 리스트"),
                ),
                ("ml_scores", models.JSONField(default=dict, verbose_name="ML 추천 점수")),
                (
                    "similar_users",
                    models.JSONField(default=list, verbose_name="유사 사용자 리스트"),
                ),
                (
                    "recommendation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="추천 생성일"),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="사용자 피드백"
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False, verbose_name="조회 여부")),
                (
                    "is_selected",
                    models.BooleanField(default=False, verbose_name="선택 여부"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML 추천 이력",
                "verbose_name_plural": "ML 추천 이력",
                "ordering": ["-recommendation_date"],
            },
        ),
    ]
