# Generated by Django 5.2.5 on 2025-08-11 07:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', '사용자'), ('bot', '봇')], max_length=10, verbose_name='메시지 타입')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('session_id', models.CharField(max_length=100, verbose_name='세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 내역',
                'verbose_name_plural': '채팅 내역',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_mode', models.CharField(choices=[('quick', '빠른 추천'), ('standard', '표준 추천'), ('detailed', '상세 추천')], max_length=10, verbose_name='추천 모드')),
                ('insurance_company', models.CharField(max_length=100, verbose_name='보험사')),
                ('insurance_name', models.CharField(max_length=200, verbose_name='보험명')),
                ('estimated_premium', models.PositiveIntegerField(verbose_name='예상 보험료')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='추천 이유')),
                ('is_selected', models.BooleanField(default=False, verbose_name='선택 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보험 추천 내역',
                'verbose_name_plural': '보험 추천 내역',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별')),
                ('car_size', models.CharField(blank=True, choices=[('small', '소형차 (1.0L 이하)'), ('medium', '중형차 (1.0L-2.0L)'), ('large', '대형차 (2.0L 이상)'), ('suv', 'SUV/트럭')], max_length=10, verbose_name='차량 크기')),
                ('annual_mileage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)], verbose_name='연간 주행거리(km)')),
                ('accident_history', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='사고 경력 횟수')),
                ('additional_coverage_interest', models.BooleanField(default=False, verbose_name='추가 특약 관심')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
            },
        ),
    ]
