# Generated by Django 5.2.5 on 2025-08-12 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancerecommendation',
            name='estimated_premium',
        ),
        migrations.RemoveField(
            model_name='insurancerecommendation',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='insurancerecommendation',
            name='insurance_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='car_size',
        ),
        migrations.AddField(
            model_name='insurancerecommendation',
            name='recommendations_data',
            field=models.JSONField(default=list, verbose_name='추천 데이터'),
        ),
        migrations.AddField(
            model_name='insurancerecommendation',
            name='selected_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='선택한 보험사'),
        ),
        migrations.AddField(
            model_name='insurancerecommendation',
            name='session_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='세션 ID'),
        ),
        migrations.AddField(
            model_name='insurancerecommendation',
            name='user_feedback',
            field=models.TextField(blank=True, verbose_name='사용자 피드백'),
        ),
        migrations.AddField(
            model_name='insurancerecommendation',
            name='user_profile_snapshot',
            field=models.JSONField(default=dict, verbose_name='사용자 프로필 스냅샷'),
        ),
        migrations.AddField(
            model_name='insurancerecommendation',
            name='user_rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='사용자 평가'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='car_type',
            field=models.CharField(blank=True, choices=[('경차', '경차'), ('소형', '소형'), ('준중형', '준중형'), ('중형', '중형'), ('대형', '대형'), ('SUV', 'SUV')], max_length=10, verbose_name='차종'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coverage_level',
            field=models.CharField(choices=[('기본', '기본'), ('표준', '표준'), ('고급', '고급'), ('프리미엄', '프리미엄')], default='표준', max_length=10, verbose_name='보장 수준'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driving_experience',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='운전 경력(년)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='residence_area',
            field=models.CharField(blank=True, choices=[('서울', '서울'), ('부산', '부산'), ('대구', '대구'), ('인천', '인천'), ('광주', '광주'), ('대전', '대전'), ('울산', '울산'), ('세종', '세종'), ('기타', '기타')], max_length=10, verbose_name='거주 지역'),
        ),
        migrations.AlterField(
            model_name='insurancerecommendation',
            name='recommendation_mode',
            field=models.CharField(choices=[('quick', '빠른 추천'), ('standard', '표준 추천'), ('detailed', '상세 추천'), ('chatbot', '챗봇 추천')], max_length=10, verbose_name='추천 모드'),
        ),
    ]
