# Generated by Django 5.2.5 on 2025-08-14 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_insurance_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='통계 날짜')),
                ('age_group_stats', models.JSONField(default=dict, verbose_name='연령대별 통계')),
                ('gender_stats', models.JSONField(default=dict, verbose_name='성별 통계')),
                ('car_type_stats', models.JSONField(default=dict, verbose_name='차종별 통계')),
                ('company_preference_stats', models.JSONField(default=dict, verbose_name='보험사별 선호도')),
                ('coverage_level_stats', models.JSONField(default=dict, verbose_name='보장 수준별 통계')),
                ('region_stats', models.JSONField(default=dict, verbose_name='지역별 통계')),
                ('total_recommendations', models.PositiveIntegerField(default=0, verbose_name='일일 추천 총 수')),
                ('total_selections', models.PositiveIntegerField(default=0, verbose_name='일일 선택된 추천 수')),
                ('average_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='평균 보험료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '추천 통계',
                'verbose_name_plural': '추천 통계',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('login', '로그인'), ('chat_start', '채팅 시작'), ('chat_message', '채팅 메시지'), ('recommendation_request', '추천 요청'), ('recommendation_view', '추천 조회'), ('recommendation_select', '추천 선택'), ('profile_update', '프로필 수정'), ('page_view', '페이지 조회')], max_length=30, verbose_name='행동 타입')),
                ('behavior_data', models.JSONField(default=dict, verbose_name='행동 데이터')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='세션 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 행동 로그',
                'verbose_name_plural': '사용자 행동 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
