# Generated by Django 5.2.5 on 2025-08-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_birth_date'),
        ('chatbot', '0007_pineconeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerecommendation',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chatbot.chatsession', verbose_name='채팅 세션'),
        ),
    ]
