# Generated by Django 4.2.7 on 2025-08-04 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="보험사명"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="보험사 코드"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "보험사",
                "verbose_name_plural": "보험사",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annual_premium", models.IntegerField(verbose_name="연간 보험료")),
                ("monthly_premium", models.IntegerField(verbose_name="월 보험료")),
                (
                    "coverage_level",
                    models.CharField(default="표준", max_length=20, verbose_name="보장 수준"),
                ),
                (
                    "coverage_details",
                    models.JSONField(default=dict, verbose_name="보장 상세 내용"),
                ),
                (
                    "special_discount",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="특별 할인"
                    ),
                ),
                (
                    "discount_rate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="할인율"
                    ),
                ),
                (
                    "penalty_rate",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="할증율"
                    ),
                ),
                ("deductible", models.JSONField(default=dict, verbose_name="자기부담금")),
                (
                    "payment_options",
                    models.JSONField(default=list, verbose_name="납입 옵션"),
                ),
                (
                    "additional_benefits",
                    models.JSONField(default=list, verbose_name="추가 혜택"),
                ),
                (
                    "customer_satisfaction",
                    models.FloatField(blank=True, null=True, verbose_name="고객만족도"),
                ),
                (
                    "claim_service_rating",
                    models.FloatField(blank=True, null=True, verbose_name="클레임 서비스 평점"),
                ),
                (
                    "calculation_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="계산일"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="insurance.insurancecompany",
                        verbose_name="보험사",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "보험 견적",
                "verbose_name_plural": "보험 견적",
                "ordering": ["-calculation_date"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=100, unique=True, verbose_name="세션 ID"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 세션",
                "verbose_name_plural": "채팅 세션",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("USER", "사용자"),
                            ("ASSISTANT", "어시스턴트"),
                            ("SYSTEM", "시스템"),
                        ],
                        max_length=10,
                        verbose_name="메시지 유형",
                    ),
                ),
                ("content", models.TextField(verbose_name="메시지 내용")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="타임스탬프"),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="insurance.chatsession",
                        verbose_name="세션",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("DOCX", "DOCX")],
                        default="PDF",
                        max_length=10,
                        verbose_name="문서 유형",
                    ),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="파일 경로")),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 날짜"),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="버전 정보"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                (
                    "pinecone_index_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Pinecone 인덱스 ID",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="파일 크기 (bytes)"
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(blank=True, null=True, verbose_name="페이지 수"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="insurance.insurancecompany",
                        verbose_name="보험사",
                    ),
                ),
            ],
            options={
                "verbose_name": "보험 약관 문서",
                "verbose_name_plural": "보험 약관 문서",
                "ordering": ["-upload_date"],
                "unique_together": {("company", "version")},
            },
        ),
    ]
