# Generated by Django 4.2.7 on 2025-08-05 08:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecompany",
            name="address",
            field=models.TextField(blank=True, verbose_name="주소"),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="city",
            field=models.CharField(blank=True, max_length=50, verbose_name="도시"),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="description",
            field=models.TextField(blank=True, verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="이메일"),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="전화번호"),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="state",
            field=models.CharField(blank=True, max_length=50, verbose_name="주/도"),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="status",
            field=models.CharField(
                choices=[("active", "활성"), ("inactive", "비활성"), ("pending", "대기")],
                default="active",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="website",
            field=models.URLField(blank=True, verbose_name="웹사이트"),
        ),
        migrations.AddField(
            model_name="insurancecompany",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="우편번호"),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="description",
            field=models.TextField(blank=True, verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "docx"]
                    )
                ],
                verbose_name="파일",
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="keywords",
            field=models.JSONField(default=list, verbose_name="키워드"),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="status",
            field=models.CharField(
                choices=[("pending", "대기"), ("approved", "승인"), ("rejected", "거부")],
                default="pending",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="tags",
            field=models.JSONField(default=list, verbose_name="태그"),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="제목"
            ),
        ),
        migrations.AlterField(
            model_name="policydocument",
            name="file_path",
            field=models.CharField(blank=True, max_length=500, verbose_name="파일 경로"),
        ),
        migrations.CreateModel(
            name="RecommendationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, verbose_name="세션 ID")),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("personalized", "개인화"),
                            ("collaborative", "협업 필터링"),
                            ("content_based", "콘텐츠 기반"),
                            ("hybrid", "하이브리드"),
                        ],
                        max_length=20,
                        verbose_name="추천 유형",
                    ),
                ),
                (
                    "recommendation_data",
                    models.JSONField(default=dict, verbose_name="추천 데이터"),
                ),
                (
                    "feedback_score",
                    models.FloatField(blank=True, null=True, verbose_name="피드백 점수"),
                ),
                (
                    "feedback_comment",
                    models.TextField(blank=True, verbose_name="피드백 코멘트"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "추천 기록",
                "verbose_name_plural": "추천 기록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, verbose_name="세션 ID")),
                ("message", models.TextField(verbose_name="사용자 메시지")),
                ("response", models.TextField(verbose_name="시스템 응답")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "사용자"),
                            ("assistant", "어시스턴트"),
                            ("system", "시스템"),
                        ],
                        default="user",
                        max_length=10,
                        verbose_name="메시지 유형",
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="메타데이터")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 기록",
                "verbose_name_plural": "채팅 기록",
                "ordering": ["-created_at"],
            },
        ),
    ]
