# Generated by Django 5.2.5 on 2025-08-11 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceMockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_company', models.CharField(max_length=100, verbose_name='보험사명')),
                ('insurance_name', models.CharField(max_length=200, verbose_name='보험명')),
                ('base_premium', models.PositiveIntegerField(verbose_name='기본 보험료')),
                ('age_20s_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='20대 가산율')),
                ('age_30s_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='30대 가산율')),
                ('age_40s_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='40대 가산율')),
                ('age_50s_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='50대 가산율')),
                ('age_60s_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='60대 가산율')),
                ('male_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='남성 가산율')),
                ('female_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='여성 가산율')),
                ('small_car_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='소형차 가산율')),
                ('medium_car_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='중형차 가산율')),
                ('large_car_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='대형차 가산율')),
                ('suv_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='SUV 가산율')),
                ('low_mileage_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='저주행 가산율')),
                ('high_mileage_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='고주행 가산율')),
                ('accident_free_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='무사고 할인율')),
                ('accident_penalty_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='사고 가산율')),
                ('additional_coverage_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='추가 특약 가산율')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '보험 Mock 데이터',
                'verbose_name_plural': '보험 Mock 데이터',
                'ordering': ['insurance_company', 'insurance_name'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='세션 제목')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문서 제목')),
                ('insurance_company', models.CharField(max_length=100, verbose_name='보험사명')),
                ('pdf_file', models.FileField(upload_to='documents/pdf/', verbose_name='PDF 파일')),
                ('txt_file', models.FileField(blank=True, null=True, upload_to='documents/txt/', verbose_name='텍스트 파일')),
                ('status', models.CharField(choices=[('uploaded', '업로드됨'), ('processing', '처리중'), ('completed', '완료'), ('error', '오류')], default='uploaded', max_length=20, verbose_name='처리 상태')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 완료 일시')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기(bytes)')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보험 약관 문서',
                'verbose_name_plural': '보험 약관 문서',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(verbose_name='청크 텍스트')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='청크 순서')),
                ('embedding_id', models.CharField(blank=True, max_length=100, verbose_name='Pinecone ID')),
                ('embedding_metadata', models.JSONField(blank=True, default=dict, verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot.insurancedocument')),
            ],
            options={
                'verbose_name': '문서 청크',
                'verbose_name_plural': '문서 청크',
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
