# Generated by Django 5.2.5 on 2025-08-11 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="보험사명"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="기관코드"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "보험사",
                "verbose_name_plural": "보험사 목록",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "채팅 세션",
                "verbose_name_plural": "채팅 세션 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="documentchunk",
            options={
                "ordering": ["document", "chunk_index"],
                "verbose_name": "문서 청크",
                "verbose_name_plural": "문서 청크 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="insurancedocument",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "보험 약관 문서",
                "verbose_name_plural": "보험 약관 문서 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="insurancemockdata",
            options={
                "ordering": ["insurance_company", "insurance_name"],
                "verbose_name": "보험 Mock 데이터",
                "verbose_name_plural": "보험 Mock 데이터 목록",
            },
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="title",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="embedding_id",
        ),
        migrations.RemoveField(
            model_name="documentchunk",
            name="embedding_metadata",
        ),
        migrations.RemoveField(
            model_name="insurancedocument",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="insurancemockdata",
            name="accident_free_rate",
        ),
        migrations.RemoveField(
            model_name="insurancemockdata",
            name="accident_penalty_rate",
        ),
        migrations.RemoveField(
            model_name="insurancemockdata",
            name="additional_coverage_rate",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일시"),
        ),
        migrations.AddField(
            model_name="insurancemockdata",
            name="accident_rate",
            field=models.FloatField(default=1.5, verbose_name="사고 할증율"),
        ),
        migrations.AddField(
            model_name="insurancemockdata",
            name="no_accident_rate",
            field=models.FloatField(default=0.8, verbose_name="무사고 할증율"),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성"),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.PositiveIntegerField(verbose_name="청크 인덱스"),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="chatbot.insurancedocument",
                verbose_name="문서",
            ),
        ),
        migrations.AlterField(
            model_name="insurancedocument",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/pdf/",
                verbose_name="PDF 파일",
            ),
        ),
        migrations.AlterField(
            model_name="insurancedocument",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="처리일시"),
        ),
        migrations.AlterField(
            model_name="insurancedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "업로드됨"),
                    ("completed", "완료"),
                    ("error", "오류"),
                ],
                default="uploaded",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="insurancedocument",
            name="title",
            field=models.CharField(max_length=200, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="insurancedocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="업로드일시"),
        ),
        migrations.AlterField(
            model_name="insurancedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="업로드자",
            ),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="age_20s_rate",
            field=models.FloatField(default=1.0, verbose_name="20대 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="age_30s_rate",
            field=models.FloatField(default=1.1, verbose_name="30대 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="age_40s_rate",
            field=models.FloatField(default=1.2, verbose_name="40대 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="age_50s_rate",
            field=models.FloatField(default=1.3, verbose_name="50대 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="age_60s_rate",
            field=models.FloatField(default=1.5, verbose_name="60대 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="female_rate",
            field=models.FloatField(default=0.9, verbose_name="여성 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="high_mileage_rate",
            field=models.FloatField(default=1.2, verbose_name="고주행 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="large_car_rate",
            field=models.FloatField(default=1.3, verbose_name="대형차 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="low_mileage_rate",
            field=models.FloatField(default=0.9, verbose_name="저주행 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="male_rate",
            field=models.FloatField(default=1.0, verbose_name="남성 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="medium_car_rate",
            field=models.FloatField(default=1.0, verbose_name="중형차 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="small_car_rate",
            field=models.FloatField(default=0.8, verbose_name="소형차 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="suv_rate",
            field=models.FloatField(default=1.2, verbose_name="SUV 할증율"),
        ),
        migrations.AlterField(
            model_name="insurancedocument",
            name="insurance_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="chatbot.insurancecompany",
                verbose_name="보험사",
            ),
        ),
        migrations.AlterField(
            model_name="insurancemockdata",
            name="insurance_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mock_data",
                to="chatbot.insurancecompany",
                verbose_name="보험사",
            ),
        ),
    ]
