# Generated by Django 5.2.5 on 2025-08-11 08:43

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_create_insurance_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancedocument',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=chatbot.models.InsuranceDocument.get_pdf_upload_path, verbose_name='PDF 파일'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to=chatbot.models.InsuranceDocument.get_txt_upload_path, verbose_name='텍스트 파일'),
        ),
    ]
