# Generated by Django 5.2.5 on 2025-08-11 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_insurancedocument_pdf_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='새로운 채팅', max_length=200, verbose_name='세션 제목'),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='메시지 내용')),
                ('is_user', models.BooleanField(default=True, verbose_name='사용자 메시지 여부')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='chatbot.chatsession', verbose_name='채팅 세션')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅 기록',
                'verbose_name_plural': '채팅 기록 목록',
                'ordering': ['created_at'],
            },
        ),
    ]
