# Generated by Django 5.2.5 on 2025-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_chatsession_session_id_chatsession_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PineconeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('read_units', models.IntegerField(default=0, help_text='읽기 단위 사용량')),
                ('write_units', models.IntegerField(default=0, help_text='쓰기 단위 사용량')),
                ('storage_gb', models.FloatField(default=0.0, help_text='저장소 사용량 (GB)')),
                ('total_queries', models.IntegerField(default=0, help_text='총 쿼리 수')),
            ],
            options={
                'verbose_name': 'Pinecone 사용량',
                'verbose_name_plural': 'Pinecone 사용량',
                'db_table': 'pinecone_usage',
            },
        ),
    ]
