# Generated by Django 5.2.5 on 2025-08-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_pineconeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='article_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='조문번호'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='청크파일경로'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='confidence_score',
            field=models.FloatField(default=0.0, verbose_name='신뢰도'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='extraction_method',
            field=models.CharField(default='rule_based', max_length=50, verbose_name='추출방법'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='키워드'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='metadata_version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='메타데이터버전'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='original_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='원본파일경로'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='페이지번호'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='processed_txt_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='처리된텍스트경로'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='review_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='검토상태'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='조항번호'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='subsection_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='항번호'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='요약'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='document_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='문서버전'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='시행일자'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='오류횟수'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='보험종류'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='legal_basis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='근거법령'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='original_file_format',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='원본파일형식'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='원본파일명'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='original_file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='원본파일크기'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='processed_txt_encoding',
            field=models.CharField(default='UTF-8', max_length=20, verbose_name='텍스트인코딩'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='processed_txt_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='처리된텍스트파일명'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='processed_txt_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='처리된텍스트파일크기'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='processing_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='처리상태'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='처리시간'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='재시도횟수'),
        ),
    ]
