# Generated by Django 5.2.5 on 2025-08-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_documentchunk_article_number_documentchunk_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='error_count',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='legal_basis',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='original_file_format',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='original_file_name',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='original_file_size',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='processed_txt_encoding',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='processed_txt_name',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='processed_txt_size',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='insurancedocument',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='chunk_file_path',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='metadata_version',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='original_file_path',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='processed_txt_path',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='subsection_number',
        ),
    ]
