# Generated by Django 5.2.5 on 2025-08-20 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_documentchunk_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('uploading', '업로드 중'), ('pdf_processing', 'PDF 처리 중'), ('text_extraction', '텍스트 추출 중'), ('chunk_creation', '청크 생성 중'), ('metadata_generation', '메타데이터 생성 중'), ('embedding_processing', 'Embedding 처리 중'), ('pinecone_upload', 'Pinecone 업로드 중'), ('completed', '완료'), ('error', '오류')], default='uploading', max_length=30, verbose_name='현재 단계')),
                ('total_chunks', models.PositiveIntegerField(default=0, verbose_name='전체 청크 수')),
                ('processed_chunks', models.PositiveIntegerField(default=0, verbose_name='처리된 청크 수')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='진행률 (%)')),
                ('log_messages', models.JSONField(default=list, verbose_name='로그 메시지')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_progress', to='chatbot.insurancedocument', verbose_name='문서')),
            ],
            options={
                'verbose_name': '처리 진행상황',
                'verbose_name_plural': '처리 진행상황 목록',
                'ordering': ['-updated_at'],
            },
        ),
    ]
